package de.heoegbr.diabeatit.data.container.event;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.media.ExifInterface;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.room.Entity;
import androidx.room.Ignore;

import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Locale;

import de.heoegbr.diabeatit.R;

/**
 * Event representing a note from the user
 */
@Entity
public class NoteEvent extends DiaryEvent {
    private static final String TAG = "NOTE_EVENT";

    /**
     * Create a new note event, supplying all fields. This constructor is mainly used by the database
     * to create the object from a table row.
     *
     * @param logEventId  Unique ID of this event, used as primary key and auto-generated by
     *                    the database.
     * @param iconId      Resource ID of an icon that may be displayed for this event
     * @param timestamp   Timestamp of the creation of the note
     * @param picturePath Path to an image attached to the note. (Optional)
     * @param note        Text supplied for this note
     */
    public NoteEvent(@Source int source, long logEventId, int iconId, Instant timestamp,
                     double value, String picturePath, String note) {
        super(TYPE_NOTE, source, logEventId, iconId, timestamp, value, picturePath, note);
    }

    /**
     * Create a new note event
     *
     * @param timestamp   Timestamp of when the note was taken
     * @param picturePath Attached image for this note
     * @param note        Text supplied
     */
    @Ignore
    public NoteEvent(@Source int source, Instant timestamp, String picturePath, String note) {
        super(TYPE_NOTE, source, R.drawable.ic_fab_note, timestamp, -1, picturePath, note);
    }

    //TODO move to utility class (including in bolus calculator)
    private static Bitmap rotateImage(Bitmap source, float angle) {
        if (angle == 0) return source;

        Matrix matrix = new Matrix();
        matrix.postRotate(angle);
        return Bitmap.createBitmap(source, 0, 0, source.getWidth(), source.getHeight(),
                matrix, true);
    }

    @Override
    public void createLayout(Context context, RelativeLayout root, boolean isSelected) {
        TextView titleV = root.findViewById(R.id.log_event_title);
        ImageView iconV = root.findViewById(R.id.log_event_icon);
        TextView timeV = root.findViewById(R.id.log_event_time);
        TextView contentV = root.findViewById(R.id.log_event_content);
        TextView noteV = root.findViewById(R.id.log_event_note);
        ImageView imgV = root.findViewById(R.id.log_event_picture);

        titleV.setText(context.getResources().getString(R.string.mn_event_title));
        iconV.setImageResource(iconId);
        timeV.setText(new SimpleDateFormat("dd.MM.YYYY HH:mm", Locale.GERMAN)
                .format(Date.from(timestamp)));

        contentV.setVisibility(View.GONE);
        noteV.setVisibility(View.VISIBLE);

        root.setBackgroundResource(isSelected ?
                R.drawable.log_event_selected_background :
                R.drawable.log_event_background);

        if (note == null)
            noteV.setVisibility(View.GONE);
        else {
            noteV.setVisibility(!note.isEmpty() ? View.VISIBLE : View.GONE);
            noteV.setText(note);
        }

        if (picturePath != null && !picturePath.isEmpty()) {
            try {
                imgV.setVisibility(View.VISIBLE);
                setPic(imgV, picturePath);
            } catch (IOException ignored) {
                Log.e(TAG, ignored.getMessage());
            }
        } else {
            imgV.setVisibility(View.GONE);
        }
    }

    //TODO move to utility class (including in bolus calculator)
    private void setPic(ImageView imageView, String imagePath) throws IOException {
        // TODO revisit picture orientation issue when time
        // https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a

        ExifInterface ei = new ExifInterface(imagePath);
        int orientation = ei.getAttributeInt(ExifInterface.TAG_ORIENTATION,
                ExifInterface.ORIENTATION_UNDEFINED);

        float rotation = 0;
        switch (orientation) {

            case ExifInterface.ORIENTATION_ROTATE_90:
                rotation = 90;
                break;

            case ExifInterface.ORIENTATION_ROTATE_180:
                rotation = 180;
                break;

            case ExifInterface.ORIENTATION_ROTATE_270:
                rotation = 270;
                break;
        }

        // Get the dimensions of the View
        int targetW;
        int targetH;
        if (rotation == 0 || rotation == 180) {
            targetW = imageView.getWidth();
            targetH = Integer.MAX_VALUE;
        } else {
            targetW = Integer.MAX_VALUE;
            targetH = imageView.getWidth();
        }

        // Get the dimensions of the bitmap
        BitmapFactory.Options bmOptions = new BitmapFactory.Options();
        bmOptions.inJustDecodeBounds = true;

        int photoW = bmOptions.outWidth;
        int photoH = bmOptions.outHeight;

        // Determine how much to scale down the image
        int scaleFactor = Math.max(photoW / targetW, photoH / targetH);

        // Decode the image file into a Bitmap sized to fill the View
        bmOptions.inJustDecodeBounds = false;
        bmOptions.inSampleSize = scaleFactor;

        Bitmap bitmap = BitmapFactory.decodeFile(imagePath, bmOptions);
//        cameraPreview.setImageBitmap(rotateImage(bitmap, rotation));
//        cameraPreviewContainer.setVisibility(View.GONE);
        imageView.setImageBitmap(rotateImage(bitmap, rotation));
    }
}