package de.heoegbr.diabeatit.db.container.event;

import android.content.Context;
import android.graphics.Bitmap;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.room.Entity;
import androidx.room.Ignore;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Locale;

import de.heoegbr.diabeatit.R;

/**
 * Event representing a note from the user
 */
@Entity
public class NoteEvent extends DiaryEvent {

    /**
     * Create a new note event, supplying all fields. This constructor is mainly used by the database
     * to create the object from a table row.
     *
     * @param logEventId Unique ID of this event, used as primary key and auto-generated by
     *                   the database.
     * @param iconId     Resource ID of an icon that may be displayed for this event
     * @param timestamp  Timestamp of the creation of the note
     * @param picture    Image attached to the note. (Optional)
     * @param note       Text supplied for this note
     */
    public NoteEvent(@Source int source, long logEventId, int iconId, Instant timestamp,
                     double value, Bitmap picture, String note) {
        super(TYPE_NOTE, source, logEventId, iconId, timestamp, value, picture, note);
    }

    /**
     * Create a new note event
     *
     * @param timestamp Timestamp of when the note was taken
     * @param picture   Attached image for this note
     * @param note      Text supplied
     */
    @Ignore
    public NoteEvent(@Source int source, Instant timestamp, Bitmap picture, String note) {
        super(TYPE_NOTE, source, R.drawable.ic_fab_note, timestamp, -1, picture, note);
    }

    @Override
    public void createLayout(Context context, RelativeLayout root, boolean isSelected) {
        TextView titleV = root.findViewById(R.id.log_event_title);
        ImageView iconV = root.findViewById(R.id.log_event_icon);
        TextView timeV = root.findViewById(R.id.log_event_time);
        TextView contentV = root.findViewById(R.id.log_event_content);
        TextView noteV = root.findViewById(R.id.log_event_note);
        ImageView imgV = root.findViewById(R.id.log_event_picture);

        titleV.setText(context.getResources().getString(R.string.mn_event_title));
        iconV.setImageResource(iconId);
        timeV.setText(new SimpleDateFormat("dd.MM.YYYY HH:mm", Locale.GERMAN)
                .format(Date.from(timestamp)));

        contentV.setVisibility(View.GONE);
        noteV.setVisibility(View.VISIBLE);
        imgV.setVisibility(picture != null ? View.VISIBLE : View.GONE);

        root.setBackgroundResource(isSelected ?
                R.drawable.log_event_selected_background :
                R.drawable.log_event_background);

        noteV.setText(note);
        if (picture != null)
            imgV.setImageBitmap(picture);
    }
}