package de.heoegbr.diabeatit.db.container.event;

import android.content.Context;
import android.graphics.Bitmap;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.room.ColumnInfo;
import androidx.room.Entity;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Locale;

import de.heoegbr.diabeatit.R;

/**
 * Event representing a note from the user
 */
@Entity
public class NoteEvent extends DiaryEvent {

	/**
	 * Image attached
	 */
	@ColumnInfo(name = "picture")
	public final Bitmap picture;
	/**
	 * Text of the note
	 */
	@ColumnInfo(name = "note")
	public final String note;

	/**
	 * Create a new note event, supplying all fields. This constructor is mainly used by the database
	 * to create the object from a table row.
	 *
	 * @param logEventId Unique ID of this event, used as primary key and auto-generated by
	 *                   the database.
	 * @param title      Title of this event
	 * @param iconId     Resource ID of an icon that may be displayed for this event
	 * @param timestamp  Timestamp of the creation of the note
	 * @param picture    Image attached to the note. (Optional)
	 * @param note       Text supplied for this note
	 */
	public NoteEvent(long logEventId, int title, int iconId, Instant timestamp, Bitmap picture, String note) {
		super(TYPE.NOTE, logEventId, title, iconId, timestamp);
		this.picture = picture;
		this.note = note;
	}

	/**
	 * Create a new note event
	 *
	 * @param timestamp Timestamp of when the note was taken
	 * @param image     Attached image for this note
	 * @param note      Text supplied
	 */
	public NoteEvent(Instant timestamp, Bitmap image, String note) {
		super(TYPE.NOTE, R.string.mn_event_title, R.drawable.ic_fab_note, timestamp);

		picture = image;
		this.note = note;
	}

	@Override
	public void createLayout(Context context, RelativeLayout root, boolean isSelected) {
		TextView titleV = root.findViewById(R.id.log_event_title);
		ImageView iconV = root.findViewById(R.id.log_event_icon);
		TextView timeV = root.findViewById(R.id.log_event_time);
		TextView contentV = root.findViewById(R.id.log_event_content);
		TextView noteV = root.findViewById(R.id.log_event_note);
		ImageView imgV = root.findViewById(R.id.log_event_picture);

		titleV.setText(title);
		iconV.setImageResource(iconId);
		timeV.setText(new SimpleDateFormat("dd.MM.YYYY HH:mm", Locale.GERMAN)
				.format(Date.from(timestamp)));

		contentV.setVisibility(View.GONE);
		noteV.setVisibility(View.VISIBLE);
		imgV.setVisibility(picture != null ? View.VISIBLE : View.GONE);

		root.setBackgroundResource(isSelected ?
				R.drawable.log_event_selected_background :
				R.drawable.log_event_background);

		noteV.setText(note);
		if (picture != null)
			imgV.setImageBitmap(picture);
	}
}