package de.heoegbr.diabeatit.db.container.event;

import android.content.Context;
import android.graphics.Bitmap;
import android.view.View;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import androidx.room.ColumnInfo;
import androidx.room.Entity;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Locale;

import de.heoegbr.diabeatit.R;

/**
 * Event representing a note from the user
 */
@Entity
public class NoteEvent extends DiaryEvent {

	/** Image attached */
	@ColumnInfo(name = "image")
	public final Bitmap IMAGE;
	/** Text of the note */
	@ColumnInfo(name = "note")
	public final String NOTE;

	/**
	 * Create a new note event, supplying all fields. This constructor is mainly used by the database
	 * to create the object from a table row.
	 * @param logEventId		Unique ID of this event, used as primary key and auto-generated by
	 *                          the database.
	 * @param TITLE				Title of this event
	 * @param ICON				Resource ID of an icon that may be displayed for this event
	 * @param TIMESTAMP			Timestamp of the creation of the note
	 * @param IMAGE				Image attached to the note. (Optional)
	 * @param NOTE				Text supplied for this note
	 */
	public NoteEvent(long logEventId, int TITLE, int ICON, Instant TIMESTAMP, Bitmap IMAGE, String NOTE) {
		super(logEventId, TITLE, ICON, TIMESTAMP);
		this.IMAGE = IMAGE;
		this.NOTE = NOTE;
	}

	/**
	 * Create a new note event
	 * @param timestamp		Timestamp of when the note was taken
	 * @param image			Attached image for this note
	 * @param note			Text supplied
	 */
	public NoteEvent(Instant timestamp, Bitmap image, String note) {

		super(R.string.mn_event_title, R.drawable.ic_fab_note, timestamp);

		IMAGE = image;
		NOTE = note;

	}

	@Override
	public void createLayout(Context context, RelativeLayout root, boolean isSelected) {

		TextView titleV = root.findViewById(R.id.log_event_title);
		ImageView iconV = root.findViewById(R.id.log_event_icon);
		TextView timeV = root.findViewById(R.id.log_event_time);
		TextView contentV = root.findViewById(R.id.log_event_content);
		TextView noteV = root.findViewById(R.id.log_event_note);
		ImageView imgV = root.findViewById(R.id.log_event_picture);

		titleV.setText(TITLE);
		iconV.setImageResource(ICON);
		timeV.setText(new SimpleDateFormat("dd.MM.YYYY HH:mm", Locale.GERMAN).format(Date.from(TIMESTAMP)));

		contentV.setVisibility(View.GONE);
		noteV.setVisibility(View.VISIBLE);
		imgV.setVisibility(IMAGE != null ? View.VISIBLE : View.GONE);

		root.setBackgroundResource(isSelected ? R.drawable.log_event_selected_background : R.drawable.log_event_background);

		noteV.setText(NOTE);
		if (IMAGE != null)
			imgV.setImageBitmap(IMAGE);

	}

}